{
 "title": "Container Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_memory_working_set_bytes, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(kube_pod_container_info{exported_namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{exported_namespace=\"$namespace\",pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "Image tags: $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{exported_namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "$image"
    }
   ]
  },
  {
   "title": "Pod created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_created{exported_namespace=\"$namespace\",pod=\"$pod\"} * 1000",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Containers CPU usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=~\"^$pod$\"}[5m])) by (container_name, pod)",
     "legendFormat": "pod: {{ pod }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",pod=~\"^$pod$\"}[5m])) by (node, rkt_container_name)",
     "legendFormat": "docker: {{ node }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",pod=~\"^$pod$\"}[5m])) by (node, rkt_container_name)",
     "legendFormat": "rkt: {{ node }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",namespace=~\"^$namespace$\",pod=~\"^$pod$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",namespace=~\"^$namespace$\",pod=~\"^$pod$\"}[5m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",namespace=~\"^$namespace$\",pod=~\"^$pod$\"}[5m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  }
 ]
}