{
 "title": "Node Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_type",
    "label": "Node Type",
    "query": {
     "query": "label_values(cloudprovider_aws_api_request_duration_seconds_sum, eks_amazonaws_com_nodegroup)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cloudprovider_aws_api_request_duration_seconds_sum{eks_amazonaws_com_nodegroup=\"$node_type\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{node=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Packets Dropped Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{instance=~\"$instance\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Packets Dropped Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{instance=~\"$instance\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Containers running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_node)(rate(node_cpu_seconds_total{mode=\"system\",kubernetes_node=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (kubernetes_node)(rate(node_cpu_seconds_total{mode='user',kubernetes_node=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (kubernetes_node)(rate(node_cpu_seconds_total{mode='iowait',kubernetes_node=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (kubernetes_node)(rate(node_cpu_seconds_total{mode=~\".*irq\",kubernetes_node=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',kubernetes_node=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',kubernetes_node=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Memory utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 4 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$instance\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$instance\"} - node_memory_MemFree_bytes{node=~\"$instance\"} - (node_memory_Cached_bytes{node=~\"$instance\"} + node_memory_Buffers_bytes{node=~\"$instance\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~\"$instance\"} + node_memory_Buffers_bytes{node=~\"$instance\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"$instance\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{node=~\"$instance\"} - node_memory_SwapFree_bytes{node=~\"$instance\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{node=~\"$instance\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{node=~\"$instance\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{node=~\"$instance\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{node=~\"$instance\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load5{node=~\"$instance\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node=~\"$instance\",device!~'rootfs'} - node_filesystem_avail_bytes{node=~\"$instance\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}